#!/usr/bin/env bash

# Runs all unit tests and performs static code analysis.
#
# Options:
#
#  --full   Include slower, more exhaustive tests and capture test coverage
#           results (outputs to .coverage.html).

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Fail when piped commands fail.
set -o pipefail

full_test=""
# Without netgo and osusergo, compilation fails under Nix.
go_test_flags=("-tags=netgo,osusergo,sqlite_json")
go_test_flags+=("-fullpath")
readonly COVERAGE_FILE_RAW=".coverage.out"
readonly COVERAGE_FILE_HTML=".coverage.html"
if [[ "$1" = "--full" ]]; then
  full_test="1"
  go_test_flags+=("-v")
  go_test_flags+=("-race")
  go_test_flags+=("--coverprofile=${COVERAGE_FILE_RAW}")
fi

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

go test "${go_test_flags[@]}" ./...
if [[ -n "$full_test" ]]; then
  go tool cover -html "${COVERAGE_FILE_RAW}" -o "${COVERAGE_FILE_HTML}"
fi

go vet ./...

# Install gci if it's not present.
GCI_PATH="$(go env GOPATH)/bin/gci"
readonly GCI_PATH
readonly GCI_VERSION="v0.13.7"
if [[ ! -f "${GCI_PATH}" ]]; then
  CGO_ENABLED=0 go install "github.com/daixiang0/gci@${GCI_VERSION}"
fi
mapfile -t GO_PACKAGE_DIRS < <(go list -f '{{.Dir}}' ./...)
readonly GO_PACKAGE_DIRS
GCI_DIFF=$("${GCI_PATH}" diff \
  --skip-generated \
  --section standard \
  --section default \
  --section "prefix(github.com/mtlynch/picoshare)" \
  "${GO_PACKAGE_DIRS[@]}")
readonly GCI_DIFF
if [[ -n "${GCI_DIFF}" ]]; then
  echo "${GCI_DIFF}"
  echo >&2 "Go imports are not grouped correctly. Run:"
  echo >&2 "  ${GCI_PATH} write --skip-generated --section standard \\"
  echo >&2 "    --section default \\"
  echo >&2 "    --section 'prefix(github.com/mtlynch/picoshare)' \\"
  echo >&2 "    \$(go list -f '{{.Dir}}' ./...)"
  exit 1
fi

# Install go-critic if it's not present.
GOCRITIC_PATH="$(go env GOPATH)/bin/go-critic"
readonly GOCRITIC_PATH
readonly GOCRITIC_VERSION="v0.14.3"
if [[ ! -f "${GOCRITIC_PATH}" ]]; then
    go install \
      "github.com/go-critic/go-critic/cmd/go-critic@${GOCRITIC_VERSION}"
fi
"${GOCRITIC_PATH}" check ./...
"${GOCRITIC_PATH}" check -enable=returnAfterHttpError ./...

# Install staticcheck if it's not present.
STATICCHECK_PATH="$(go env GOPATH)/bin/staticcheck"
readonly STATICCHECK_PATH
readonly STATICCHECK_VERSION="v0.7.0"
if [[ ! -f "${STATICCHECK_PATH}" ]]; then
    go install \
      "honnef.co/go/tools/cmd/staticcheck@${STATICCHECK_VERSION}"
fi
"${STATICCHECK_PATH}" ./...

# Install errcheck if it's not present.
ERRCHECK_PATH="$(go env GOPATH)/bin/errcheck"
readonly ERRCHECK_PATH
readonly ERRCHECK_VERSION="v1.10.0"
if [[ ! -f "${ERRCHECK_PATH}" ]]; then
    go install \
      "github.com/kisielk/errcheck@${ERRCHECK_VERSION}"
fi
"${ERRCHECK_PATH}" -ignoretests ./...
